
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izyanoeggqrptderqrgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6eWFub2VnZ3FycHRkZXJxcmd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5OTUzMjgsImV4cCI6MjA1OTU3MTMyOH0.FTSyXInu6LFfbfBqCgdk9_UCpwSh8KwEq3hhJB_0i3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
